STRING = "string"
JSON = "json"
ADJECTIVE = "ADJ"
ADPOSITION = "ADP"
ADVERB = "ADV"
AUXILIARY = "AUX"
CONJUNCTION = "CCONJ"
DETERMINER = "DET"
INTERJECTION = "INTJ"
NOUN = "NOUN"
NUMERAL = "NUM"
PARTICLE = "PART"
PRONOUN = "PRON"
PROPER_NOUN = "PROPN"
PUNCTUATION = "PUNCT"
SUBORDINATING_CONJUNCTION = "SCONJ"
SYMBOL = "SYM"
VERB = "VERB"
OTHER = "X"
PREPOSITIONAL_PHRASE = "PP"
VERB_PHRASE = "VP"
NOUN_PHRASE = "NP"
S_CLAUSE = "S"
SBAR_CLAUSE = "SBAR"
SBARQ_CLAUSE = "SBARQ"
SINV_CLAUSE = "SINV"
SQ_CLAUSE = "SQ"
VERB_PHRASE_LANGUAGE_MAP = {"fr": "VN", "default": VERB_PHRASE}
SUBORD_CLAUSE_LANGUAGE_MAP = {
    "fr": "Ssub",
    "zh-hant": ["CP", "CP-Q"],
    "default": [SBAR_CLAUSE],
}
CLAUSES_LANGUAGE_MAP = {
    "fr": ["VPinf", "VPpart", "Srel", "Ssub", "Sint"],
    "zh-hant": ["IP", "CP", "IP-Q", "CP-Q", "IP-IMP"],
    "default": [S_CLAUSE, SBAR_CLAUSE, SBARQ_CLAUSE, SINV_CLAUSE, SQ_CLAUSE],
}
NOT_AVAILABLE = "NA"
